I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 18, in script
    e "Once you add a story, pictures, and music, you can release it to the world!"
  File "renpy/common/00nvl_mode.rpy", line 264, in do_display
    page = self.clear or nvl_clear_next()
  File "renpy/common/00nvl_mode.rpy", line 226, in nvl_clear_next
    scry = scry.next()
AttributeError: 'StoreModule' object has no attribute 'n'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 18, in script
    e "Once you add a story, pictures, and music, you can release it to the world!"
  File "/home/cecille/renpy-6.18.3-sdk/renpy/ast.py", line 593, in execute
    renpy.exports.say(who, what, interact=self.interact)
  File "/home/cecille/renpy-6.18.3-sdk/renpy/exports.py", line 999, in say
    who(what, interact=interact)
  File "/home/cecille/renpy-6.18.3-sdk/renpy/character.py", line 826, in __call__
    self.do_display(who, what, cb_args=self.cb_args, **display_args)
  File "renpy/common/00nvl_mode.rpy", line 264, in do_display
    page = self.clear or nvl_clear_next()
  File "renpy/common/00nvl_mode.rpy", line 226, in nvl_clear_next
    scry = scry.next()
  File "/home/cecille/renpy-6.18.3-sdk/renpy/ast.py", line 297, in next
    return self._next.scry()
  File "/home/cecille/renpy-6.18.3-sdk/renpy/ast.py", line 630, in scry
    who = getattr(renpy.store, self.who)
AttributeError: 'StoreModule' object has no attribute 'n'

Linux-3.13.0-43-generic-x86_64-with-debian-jessie-sid
Ren'Py 6.18.3.761
complexbound 0.0
